name: Notify Cosmo

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to cosmo
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.COSMO_DISPATCH_TOKEN }}
          repository: patflynn/cosmo
          event-type: klaus-updated
